const mongoose = require('mongoose')

const formTemplate = new mongoose.Schema({
    name:{
        type:String,
        reuired:true
    },
    email:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    user:{
        type:String,
        required:true
    },
    companyname:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    company:{
        type:String,
        required:true
    },
    solution:{
        type:String,
        required:true
    },
    advantage:{
        type:String,
        required:true
    },
    potential:{
        type:String,
        required:true
    },
    proposal:{
        type:String,
        required:true
    },
    team:{
        type:String,
        required:true
    },
    problem:{
        type:String,
        required:true
    },
    proposition:{
        type:String,
        required:true
    },
    revenue:{
        type:String,
        required:true
    },
    services:{
        type:String,
        required:true
    },
    image:{
        type:String,
        required:true
    },
    status:{
        type:String,
        default:"new"
    },
    date:{
        type:Date,
        default:Date.now
    }
    
})

module.exports = mongoose.model('incuform',formTemplate)